//flashcardSets
export const START_LOADING_FLASHCARDSETS = "START_LOADING_FLASHCARDSETS";
export const SUCCESSFULLY_LOADED_FLASHCARDSETS =
  "SUCCESSFULLY_LOADED_FLASHCARDSETS";
export const SELECT_FLASHCARDSET_BY_ID = "SELECT_FLASHCARDSET_BY_ID";
export const SELECT_FLASHCARDSET = "SELECT_FLASHCARDSET";
export const ADD_FLASHCARDSET = "ADD_FLASHCARDSET";
export const SUCCESSFULLY_CREATED_FLASHCARD_SET =
  "SUCCESSFULLY_CREATED_FLASHCARD_SET";
export const DELETE_FLASHCARDSET = "DELETE_FLASHCARDSET";
export const ADDING_FLASHCARDSET_STATE = "ADDING_FLASHCARDSET_STATE";
export const NEW_FLASHCARDSET_TITLE = "NEW_FLASHCARDSET_TITLE";

//flashcards
export const START_LOADING_FLASHCARDS = "START_LOADING_FLASHCARDS";
export const SUCCESSFULLY_LOADED_FLASHCARDS = "SUCCESSFULLY_LOADED_FLASHCARDS";
export const ADDING_FLASHCARD = "ADDING_FLASHCARD";
export const SUCCESSFULLY_CREATED_FLASHCARD = "SUCCESSFULLY_CREATED_FLASHCARD";
export const DELETE_FLASHCARD = "DELETE_FLASHCARD";
export const FAILED_LOADING_FLASHCARDSETS = "FAILED_LOADING_FLASHCARDSETS";
